# Build stage
FROM node:18 AS build

WORKDIR /app
COPY app/package.json app/package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

# Production stage
FROM node:18-slim

WORKDIR /app
COPY --from=build /app ./app
CMD ["node", "app/server.js"]
